"""HTTP 서비스 조립 facade."""

from __future__ import annotations

from server.app.api.http.wiring.builders import (
    auth_context,
    events_history,
    reporting,
    runtime,
)

build_auth_service = auth_context.build_auth_service
build_session_service = auth_context.build_session_service
build_meeting_context_service = auth_context.build_meeting_context_service
build_context_catalog_service = auth_context.build_context_catalog_service
build_context_resolution_service = auth_context.build_context_resolution_service
build_participant_followup_service = auth_context.build_participant_followup_service
build_participation_query_service = auth_context.build_participation_query_service

build_runtime_monitor_service = runtime.build_runtime_monitor_service
build_session_finalization_service = runtime.build_session_finalization_service
build_post_meeting_pipeline_service = runtime.build_post_meeting_pipeline_service
build_text_input_pipeline_service = runtime.build_text_input_pipeline_service

build_event_management_service = events_history.build_event_management_service
build_event_lifecycle_service = events_history.build_event_lifecycle_service
build_history_query_service = events_history.build_history_query_service

build_report_service = reporting.build_report_service
build_report_generation_job_service = reporting.build_report_generation_job_service
build_report_knowledge_indexing_service = (
    reporting.build_report_knowledge_indexing_service
)
build_retrieval_query_service = reporting.build_retrieval_query_service
build_ollama_embedding_service = reporting.build_ollama_embedding_service
build_report_share_service = reporting.build_report_share_service
build_session_overview_service = reporting.build_session_overview_service
