/** 오버레이 런타임의 elements 모듈이다. */
export const elements = {
    authGate: document.querySelector("#auth-gate"),
    serverUrlInput: document.querySelector("#server-url-input"),
    liveServerUrlInput: document.querySelector("#live-server-url-input"),
    authRefreshButton: document.querySelector("#auth-refresh-btn"),
    authModeBadge: document.querySelector("#auth-mode-badge"),
    authServerBadge: document.querySelector("#auth-server-badge"),
    authBootstrapNote: document.querySelector("#auth-bootstrap-note"),
    authBootstrapCommand: document.querySelector("#auth-bootstrap-command"),
    authLoginForm: document.querySelector("#auth-login-form"),
    authLoginId: document.querySelector("#auth-login-id"),
    authPassword: document.querySelector("#auth-password"),
    authRememberCheckbox: document.querySelector("#auth-remember-login"),
    authLoginButton: document.querySelector("#auth-login-btn"),
    authStatusText: document.querySelector("#auth-status-text"),
    authUserSummary: document.querySelector("#auth-user-summary"),
    logoutButton: document.querySelector("#logout-btn"),

    captionBox: document.querySelector("#caption-box"),
    captionToggle: document.querySelector("#caption-toggle"),
    captionBody: document.querySelector("#caption-body"),
    captionFeed: document.querySelector("#caption-feed"),
    liveSpeaker: document.querySelector("#live-speaker"),
    liveText: document.querySelector("#live-text"),
    statusDot: document.querySelector("#status-dot"),
    workspaceCaptionCurrent: document.querySelector("#workspace-caption-current"),
    workspaceCaptionRecent: document.querySelector("#workspace-caption-recent"),

    togglePanel: document.querySelector("#toggle-panel"),
    closePanel: document.querySelector("#close-panel"),
    openWebWorkspaceButton: document.querySelector("#open-web-workspace-btn"),
    workspace: document.querySelector("#workspace"),
    tabs: document.querySelectorAll(".workspace-tab"),
    tabBodies: document.querySelectorAll(".workspace-body"),

    sessionTitle: document.querySelector("#session-title"),
    sessionSource: document.querySelector("#session-source"),
    sessionParticipants: document.querySelector("#session-participants"),
    sessionAccount: document.querySelector("#session-account"),
    sessionContact: document.querySelector("#session-contact"),
    sessionThread: document.querySelector("#session-thread"),
    sessionContextRefreshButton: document.querySelector("#session-context-refresh-btn"),
    sessionContextStatus: document.querySelector("#session-context-status"),
    createSessionButton: document.querySelector("#create-session-btn"),
    startSessionButton: document.querySelector("#start-session-btn"),
    endSessionButton: document.querySelector("#end-session-btn"),
    sessionInfo: document.querySelector("#session-info"),
    sessionId: document.querySelector("#session-id"),
    sessionStatus: document.querySelector("#session-status"),
    liveConnectionStatus: document.querySelector("#live-connection-status"),
    sessionActiveSources: document.querySelector("#session-active-sources"),
    sessionParticipantsSummary: document.querySelector("#session-participants-summary"),
    sessionParticipantCandidatesPanel: document.querySelector("#session-participant-candidates-panel"),
    sessionParticipantCandidatesList: document.querySelector("#session-participant-candidates-list"),
    sessionParticipantCandidatesStatus: document.querySelector("#session-participant-candidates-status"),
    sessionParticipantFollowupsPanel: document.querySelector("#session-participant-followups-panel"),
    sessionParticipantFollowupsList: document.querySelector("#session-participant-followups-list"),
    sessionParticipantFollowupsStatus: document.querySelector("#session-participant-followups-status"),
    currentTopic: document.querySelector("#current-topic"),
    runtimeOverall: document.querySelector("#runtime-overall"),
    runtimeClient: document.querySelector("#runtime-client"),
    runtimeServer: document.querySelector("#runtime-server"),
    runtimeStt: document.querySelector("#runtime-stt"),
    monitorActiveSessions: document.querySelector("#monitor-active-sessions"),
    monitorAvgDelay: document.querySelector("#monitor-avg-delay"),
    monitorMaxDelay: document.querySelector("#monitor-max-delay"),
    monitorLateFinals: document.querySelector("#monitor-late-finals"),
    monitorBackpressure: document.querySelector("#monitor-backpressure"),
    monitorThroughput: document.querySelector("#monitor-throughput"),
    monitorLastProcessed: document.querySelector("#monitor-last-processed"),
    monitorLastError: document.querySelector("#monitor-last-error"),

    questionCount: document.querySelector("#question-count"),
    decisionCount: document.querySelector("#decision-count"),
    actionCount: document.querySelector("#action-count"),
    riskCount: document.querySelector("#risk-count"),
    refreshEventsButton: document.querySelector("#refresh-events-btn"),
    eventEditor: document.querySelector("#event-editor"),
    eventEditorTitle: document.querySelector("#event-editor-title"),
    eventEditTitle: document.querySelector("#event-edit-title"),
    saveEventEditButton: document.querySelector("#save-event-edit-btn"),
    cancelEventEditButton: document.querySelector("#cancel-event-edit-btn"),
    questionsList: document.querySelector("#questions-list"),
    decisionsList: document.querySelector("#decisions-list"),
    actionsList: document.querySelector("#actions-list"),
    risksList: document.querySelector("#risks-list"),

    reportStatus: document.querySelector("#report-status"),
    reportFilePath: document.querySelector("#report-file-path"),
    reportWarning: document.querySelector("#report-warning"),
    openWebReportsButton: document.querySelector("#open-web-reports-btn"),
    openWebHistoryButton: document.querySelector("#open-web-history-btn"),
    openWebAssistantButton: document.querySelector("#open-web-assistant-btn"),

    eventCardTemplate: document.querySelector("#event-card-template"),
};
