export const elements = {
    captionBox: document.querySelector("#caption-box"),
    captionToggle: document.querySelector("#caption-toggle"),
    captionBody: document.querySelector("#caption-body"),
    captionFeed: document.querySelector("#caption-feed"),
    liveSpeaker: document.querySelector("#live-speaker"),
    liveText: document.querySelector("#live-text"),
    statusDot: document.querySelector("#status-dot"),

    togglePanel: document.querySelector("#toggle-panel"),
    closePanel: document.querySelector("#close-panel"),
    workspace: document.querySelector("#workspace"),
    tabs: document.querySelectorAll(".workspace-tab"),
    tabBodies: document.querySelectorAll(".workspace-body"),

    sessionTitle: document.querySelector("#session-title"),
    sessionSource: document.querySelector("#session-source"),
    createSessionButton: document.querySelector("#create-session-btn"),
    endSessionButton: document.querySelector("#end-session-btn"),
    sessionInfo: document.querySelector("#session-info"),
    sessionId: document.querySelector("#session-id"),
    sessionStatus: document.querySelector("#session-status"),
    sessionActiveSources: document.querySelector("#session-active-sources"),
    currentTopic: document.querySelector("#current-topic"),
    runtimeOverall: document.querySelector("#runtime-overall"),
    runtimeFrontend: document.querySelector("#runtime-frontend"),
    runtimeBackend: document.querySelector("#runtime-backend"),
    runtimeStt: document.querySelector("#runtime-stt"),

    devTextInput: document.querySelector("#dev-text-input"),
    connectDevTextButton: document.querySelector("#connect-dev-text-btn"),
    sendDevTextButton: document.querySelector("#send-dev-text-btn"),
    devTextConnection: document.querySelector("#dev-text-connection"),

    questionCount: document.querySelector("#question-count"),
    decisionCount: document.querySelector("#decision-count"),
    actionCount: document.querySelector("#action-count"),
    riskCount: document.querySelector("#risk-count"),
    refreshEventsButton: document.querySelector("#refresh-events-btn"),
    questionsList: document.querySelector("#questions-list"),
    decisionsList: document.querySelector("#decisions-list"),
    actionsList: document.querySelector("#actions-list"),
    risksList: document.querySelector("#risks-list"),

    reportAudioPath: document.querySelector("#report-audio-path"),
    generateReportButton: document.querySelector("#generate-report-btn"),
    generatePdfReportButton: document.querySelector("#generate-pdf-report-btn"),
    regenerateReportsButton: document.querySelector("#regenerate-reports-btn"),
    loadLatestReportButton: document.querySelector("#load-latest-report-btn"),
    openReportButton: document.querySelector("#open-report-btn"),
    reportStatus: document.querySelector("#report-status"),
    reportFilePath: document.querySelector("#report-file-path"),
    reportVersion: document.querySelector("#report-version"),
    reportHistoryCount: document.querySelector("#report-history-count"),
    reportHistoryList: document.querySelector("#report-history-list"),
    speakerTranscriptCount: document.querySelector("#speaker-transcript-count"),
    speakerEventCount: document.querySelector("#speaker-event-count"),
    speakerTranscriptList: document.querySelector("#speaker-transcript-list"),
    speakerEventsList: document.querySelector("#speaker-events-list"),

    eventCardTemplate: document.querySelector("#event-card-template"),
    speakerTranscriptTemplate: document.querySelector("#speaker-transcript-template"),
};
