"""오디오 영역의 speech to text factory 서비스를 제공한다."""
from __future__ import annotations

from server.app.services.audio.stt.factory_builders import (
    SpeechToTextBuildOptions,
    build_backend_builders,
    build_hybrid_local_streaming,
)
from server.app.services.audio.stt.transcription import SpeechToTextService


def create_speech_to_text_service(
    backend_name: str,
    model_id: str = "amd/whisper-small-onnx-npu",
    model_path: str | None = None,
    base_model_id: str | None = None,
    installation_path: str | None = None,
    encoder_model_path: str | None = None,
    decoder_model_path: str | None = None,
    encoder_rai_path: str | None = None,
    base_url: str = "http://127.0.0.1:8001/v1/audio",
    api_key: str | None = None,
    timeout_seconds: float = 20.0,
    language: str | None = "ko",
    initial_prompt: str | None = None,
    device: str = "auto",
    compute_type: str = "default",
    cpu_threads: int = 0,
    beam_size: int = 1,
    sample_rate_hz: int = 16000,
    sample_width_bytes: int = 2,
    channels: int = 1,
    silence_rms_threshold: float = 0.003,
    partial_buffer_ms: int = 900,
    partial_emit_interval_ms: int = 240,
    partial_min_rms_threshold: float = 0.004,
    partial_agreement_window: int = 2,
    partial_agreement_min_count: int = 2,
    partial_min_stable_chars: int = 4,
    partial_min_growth_chars: int = 2,
    partial_backtrack_tolerance_chars: int = 2,
    partial_commit_min_chars_without_boundary: int = 6,
    partial_backend_name: str | None = None,
    partial_model_id: str | None = None,
    partial_model_path: str | None = None,
    partial_device: str | None = None,
    partial_compute_type: str | None = None,
    partial_cpu_threads: int | None = None,
    partial_beam_size: int | None = None,
    final_backend_name: str | None = None,
    final_model_id: str | None = None,
    final_model_path: str | None = None,
    final_device: str | None = None,
    final_compute_type: str | None = None,
    final_cpu_threads: int | None = None,
    final_beam_size: int | None = None,
) -> SpeechToTextService:
    """설정값에 맞는 STT 서비스를 반환한다."""

    options = SpeechToTextBuildOptions(
        backend_name=backend_name,
        model_id=model_id,
        model_path=model_path,
        base_model_id=base_model_id,
        installation_path=installation_path,
        encoder_model_path=encoder_model_path,
        decoder_model_path=decoder_model_path,
        encoder_rai_path=encoder_rai_path,
        base_url=base_url,
        api_key=api_key,
        timeout_seconds=timeout_seconds,
        language=language,
        initial_prompt=initial_prompt,
        device=device,
        compute_type=compute_type,
        cpu_threads=cpu_threads,
        beam_size=beam_size,
        sample_rate_hz=sample_rate_hz,
        sample_width_bytes=sample_width_bytes,
        channels=channels,
        silence_rms_threshold=silence_rms_threshold,
        partial_buffer_ms=partial_buffer_ms,
        partial_emit_interval_ms=partial_emit_interval_ms,
        partial_min_rms_threshold=partial_min_rms_threshold,
        partial_agreement_window=partial_agreement_window,
        partial_agreement_min_count=partial_agreement_min_count,
        partial_min_stable_chars=partial_min_stable_chars,
        partial_min_growth_chars=partial_min_growth_chars,
        partial_backtrack_tolerance_chars=partial_backtrack_tolerance_chars,
        partial_commit_min_chars_without_boundary=partial_commit_min_chars_without_boundary,
        partial_backend_name=partial_backend_name,
        partial_model_id=partial_model_id,
        partial_model_path=partial_model_path,
        partial_device=partial_device,
        partial_compute_type=partial_compute_type,
        partial_cpu_threads=partial_cpu_threads,
        partial_beam_size=partial_beam_size,
        final_backend_name=final_backend_name,
        final_model_id=final_model_id,
        final_model_path=final_model_path,
        final_device=final_device,
        final_compute_type=final_compute_type,
        final_cpu_threads=final_cpu_threads,
        final_beam_size=final_beam_size,
    )
    return create_speech_to_text_service_from_options(options)


def create_speech_to_text_service_from_options(options: SpeechToTextBuildOptions) -> SpeechToTextService:
    """옵션 객체 기반으로 STT 서비스를 생성한다."""

    builders = build_backend_builders(options, create_service=create_speech_to_text_service)
    if options.backend_name not in builders:
        raise ValueError(f"지원하지 않는 stt backend입니다: {options.backend_name}")
    return builders[options.backend_name]()


def _build_hybrid_local_streaming(
    *,
    model_id: str,
    model_path: str | None,
    language: str | None,
    device: str,
    compute_type: str,
    cpu_threads: int,
    beam_size: int,
    sample_rate_hz: int,
    sample_width_bytes: int,
    channels: int,
    silence_rms_threshold: float,
    partial_buffer_ms: int,
    partial_emit_interval_ms: int,
    partial_min_rms_threshold: float,
    partial_agreement_window: int,
    partial_agreement_min_count: int,
    partial_min_stable_chars: int,
    partial_min_growth_chars: int,
    partial_backtrack_tolerance_chars: int,
    partial_commit_min_chars_without_boundary: int,
    partial_backend_name: str | None,
    partial_model_id: str | None,
    partial_model_path: str | None,
    partial_device: str | None,
    partial_compute_type: str | None,
    partial_cpu_threads: int | None,
    partial_beam_size: int | None,
    final_backend_name: str | None,
    final_model_id: str | None,
    final_model_path: str | None,
    final_device: str | None,
    final_compute_type: str | None,
    final_cpu_threads: int | None,
    final_beam_size: int | None,
) -> SpeechToTextService:
    """호환용 하이브리드 빌더."""

    return build_hybrid_local_streaming(
        create_service=create_speech_to_text_service,
        model_id=model_id,
        model_path=model_path,
        language=language,
        device=device,
        compute_type=compute_type,
        cpu_threads=cpu_threads,
        beam_size=beam_size,
        sample_rate_hz=sample_rate_hz,
        sample_width_bytes=sample_width_bytes,
        channels=channels,
        silence_rms_threshold=silence_rms_threshold,
        partial_buffer_ms=partial_buffer_ms,
        partial_emit_interval_ms=partial_emit_interval_ms,
        partial_min_rms_threshold=partial_min_rms_threshold,
        partial_agreement_window=partial_agreement_window,
        partial_agreement_min_count=partial_agreement_min_count,
        partial_min_stable_chars=partial_min_stable_chars,
        partial_min_growth_chars=partial_min_growth_chars,
        partial_backtrack_tolerance_chars=partial_backtrack_tolerance_chars,
        partial_commit_min_chars_without_boundary=partial_commit_min_chars_without_boundary,
        partial_backend_name=partial_backend_name,
        partial_model_id=partial_model_id,
        partial_model_path=partial_model_path,
        partial_device=partial_device,
        partial_compute_type=partial_compute_type,
        partial_cpu_threads=partial_cpu_threads,
        partial_beam_size=partial_beam_size,
        final_backend_name=final_backend_name,
        final_model_id=final_model_id,
        final_model_path=final_model_path,
        final_device=final_device,
        final_compute_type=final_compute_type,
        final_cpu_threads=final_cpu_threads,
        final_beam_size=final_beam_size,
    )


__all__ = [
    "SpeechToTextBuildOptions",
    "create_speech_to_text_service",
    "create_speech_to_text_service_from_options",
]
