export const elements = {
    captionBox: document.querySelector("#caption-box"),
    captionToggle: document.querySelector("#caption-toggle"),
    captionBody: document.querySelector("#caption-body"),
    captionFeed: document.querySelector("#caption-feed"),
    liveSpeaker: document.querySelector("#live-speaker"),
    liveText: document.querySelector("#live-text"),
    statusDot: document.querySelector("#status-dot"),

    togglePanel: document.querySelector("#toggle-panel"),
    closePanel: document.querySelector("#close-panel"),
    workspace: document.querySelector("#workspace"),
    tabs: document.querySelectorAll(".workspace-tab"),
    tabBodies: document.querySelectorAll(".workspace-body"),

    sessionTitle: document.querySelector("#session-title"),
    sessionSource: document.querySelector("#session-source"),
    createSessionButton: document.querySelector("#create-session-btn"),
    endSessionButton: document.querySelector("#end-session-btn"),
    sessionInfo: document.querySelector("#session-info"),
    sessionId: document.querySelector("#session-id"),
    sessionStatus: document.querySelector("#session-status"),
    liveConnectionStatus: document.querySelector("#live-connection-status"),
    sessionActiveSources: document.querySelector("#session-active-sources"),
    currentTopic: document.querySelector("#current-topic"),
    runtimeOverall: document.querySelector("#runtime-overall"),
    runtimeFrontend: document.querySelector("#runtime-frontend"),
    runtimeBackend: document.querySelector("#runtime-backend"),
    runtimeStt: document.querySelector("#runtime-stt"),

    questionCount: document.querySelector("#question-count"),
    decisionCount: document.querySelector("#decision-count"),
    actionCount: document.querySelector("#action-count"),
    riskCount: document.querySelector("#risk-count"),
    refreshEventsButton: document.querySelector("#refresh-events-btn"),
    eventEditor: document.querySelector("#event-editor"),
    eventEditorTitle: document.querySelector("#event-editor-title"),
    eventEditTitle: document.querySelector("#event-edit-title"),
    saveEventEditButton: document.querySelector("#save-event-edit-btn"),
    cancelEventEditButton: document.querySelector("#cancel-event-edit-btn"),
    questionsList: document.querySelector("#questions-list"),
    decisionsList: document.querySelector("#decisions-list"),
    actionsList: document.querySelector("#actions-list"),
    risksList: document.querySelector("#risks-list"),

    reportFormatSelect: document.querySelector("#report-format-select"),
    generateReportButton: document.querySelector("#generate-report-btn"),
    reportStatus: document.querySelector("#report-status"),
    reportFilePath: document.querySelector("#report-file-path"),
    reportVersion: document.querySelector("#report-version"),

    eventCardTemplate: document.querySelector("#event-card-template"),
};
