"""오디오 영역의 registry 서비스를 제공한다."""
from __future__ import annotations

from collections.abc import Callable

from server.app.services.audio.stt.transcription import SpeechToTextService

from . import basic, hybrid, local, streaming
from .options import SpeechToTextBuildOptions


def build_backend_builders(
    options: SpeechToTextBuildOptions,
    *,
    create_service: Callable[..., SpeechToTextService],
) -> dict[str, Callable[[], SpeechToTextService]]:
    """옵션에 맞는 backend 빌더 맵을 구성한다."""

    return {
        "placeholder": basic.build_placeholder,
        "openai_compatible_audio": lambda: basic.build_openai_compatible_audio(
            model_id=options.model_id,
            base_url=options.base_url,
            api_key=options.api_key,
            timeout_seconds=options.timeout_seconds,
            language=options.language,
            sample_rate_hz=options.sample_rate_hz,
            sample_width_bytes=options.sample_width_bytes,
            channels=options.channels,
        ),
        "amd_whisper_npu": lambda: local.build_amd_whisper_npu(
            model_id=options.model_id,
            model_path=options.model_path,
            base_model_id=options.base_model_id,
            installation_path=options.installation_path,
            encoder_model_path=options.encoder_model_path,
            decoder_model_path=options.decoder_model_path,
            encoder_rai_path=options.encoder_rai_path,
            language=options.language,
            sample_rate_hz=options.sample_rate_hz,
            sample_width_bytes=options.sample_width_bytes,
            channels=options.channels,
            silence_rms_threshold=options.silence_rms_threshold,
        ),
        "faster_whisper": lambda: local.build_faster_whisper(
            model_id=options.model_id,
            model_path=options.model_path,
            language=options.language,
            initial_prompt=options.initial_prompt,
            device=options.device,
            compute_type=options.compute_type,
            cpu_threads=options.cpu_threads,
            beam_size=options.beam_size,
            sample_rate_hz=options.sample_rate_hz,
            sample_width_bytes=options.sample_width_bytes,
            channels=options.channels,
            silence_rms_threshold=options.silence_rms_threshold,
        ),
        "faster_whisper_streaming": lambda: streaming.build_faster_whisper_streaming(
            model_id=options.model_id,
            model_path=options.model_path,
            language=options.language,
            initial_prompt=options.initial_prompt,
            device=options.device,
            compute_type=options.compute_type,
            cpu_threads=options.cpu_threads,
            beam_size=options.beam_size,
            sample_rate_hz=options.sample_rate_hz,
            sample_width_bytes=options.sample_width_bytes,
            channels=options.channels,
            silence_rms_threshold=options.silence_rms_threshold,
            partial_buffer_ms=options.partial_buffer_ms,
            partial_emit_interval_ms=options.partial_emit_interval_ms,
            partial_min_rms_threshold=options.partial_min_rms_threshold,
            partial_agreement_window=options.partial_agreement_window,
            partial_agreement_min_count=options.partial_agreement_min_count,
            partial_min_stable_chars=options.partial_min_stable_chars,
            partial_min_growth_chars=options.partial_min_growth_chars,
            partial_backtrack_tolerance_chars=options.partial_backtrack_tolerance_chars,
            partial_commit_min_chars_without_boundary=options.partial_commit_min_chars_without_boundary,
        ),
        "sherpa_onnx_streaming": lambda: streaming.build_sherpa_onnx_streaming(
            model_id=options.model_id,
            model_path=options.model_path,
            language=options.language,
            device=options.device,
            cpu_threads=options.cpu_threads,
            beam_size=options.beam_size,
            sample_rate_hz=options.sample_rate_hz,
            sample_width_bytes=options.sample_width_bytes,
            channels=options.channels,
            partial_emit_interval_ms=options.partial_emit_interval_ms,
            partial_agreement_window=options.partial_agreement_window,
            partial_agreement_min_count=options.partial_agreement_min_count,
            partial_min_stable_chars=options.partial_min_stable_chars,
            partial_min_growth_chars=options.partial_min_growth_chars,
            partial_backtrack_tolerance_chars=options.partial_backtrack_tolerance_chars,
            partial_commit_min_chars_without_boundary=options.partial_commit_min_chars_without_boundary,
        ),
        "hybrid_local_streaming": lambda: hybrid.build_hybrid_local_streaming(
            create_service=create_service,
            model_id=options.model_id,
            model_path=options.model_path,
            language=options.language,
            device=options.device,
            compute_type=options.compute_type,
            cpu_threads=options.cpu_threads,
            beam_size=options.beam_size,
            sample_rate_hz=options.sample_rate_hz,
            sample_width_bytes=options.sample_width_bytes,
            channels=options.channels,
            silence_rms_threshold=options.silence_rms_threshold,
            partial_buffer_ms=options.partial_buffer_ms,
            partial_emit_interval_ms=options.partial_emit_interval_ms,
            partial_min_rms_threshold=options.partial_min_rms_threshold,
            partial_agreement_window=options.partial_agreement_window,
            partial_agreement_min_count=options.partial_agreement_min_count,
            partial_min_stable_chars=options.partial_min_stable_chars,
            partial_min_growth_chars=options.partial_min_growth_chars,
            partial_backtrack_tolerance_chars=options.partial_backtrack_tolerance_chars,
            partial_commit_min_chars_without_boundary=options.partial_commit_min_chars_without_boundary,
            partial_backend_name=options.partial_backend_name,
            partial_model_id=options.partial_model_id,
            partial_model_path=options.partial_model_path,
            partial_device=options.partial_device,
            partial_compute_type=options.partial_compute_type,
            partial_cpu_threads=options.partial_cpu_threads,
            partial_beam_size=options.partial_beam_size,
            final_backend_name=options.final_backend_name,
            final_model_id=options.final_model_id,
            final_model_path=options.final_model_path,
            final_device=options.final_device,
            final_compute_type=options.final_compute_type,
            final_cpu_threads=options.final_cpu_threads,
            final_beam_size=options.final_beam_size,
        ),
        "moonshine": lambda: local.build_moonshine(
            model_id=options.model_id,
            model_path=options.model_path,
            language=options.language,
            sample_rate_hz=options.sample_rate_hz,
            sample_width_bytes=options.sample_width_bytes,
            channels=options.channels,
            silence_rms_threshold=options.silence_rms_threshold,
        ),
        "moonshine_streaming": lambda: streaming.build_moonshine_streaming(
            model_id=options.model_id,
            model_path=options.model_path,
            language=options.language,
            sample_rate_hz=options.sample_rate_hz,
            sample_width_bytes=options.sample_width_bytes,
            channels=options.channels,
            silence_rms_threshold=options.silence_rms_threshold,
            partial_buffer_ms=options.partial_buffer_ms,
            partial_emit_interval_ms=options.partial_emit_interval_ms,
            partial_min_rms_threshold=options.partial_min_rms_threshold,
            partial_agreement_window=options.partial_agreement_window,
            partial_agreement_min_count=options.partial_agreement_min_count,
            partial_min_stable_chars=options.partial_min_stable_chars,
            partial_min_growth_chars=options.partial_min_growth_chars,
        ),
    }
